### ISSUE TITLE
Abandoned packages

### ISSUE THREAD

**Issue by RickCogley** [statamic/starter-kit-cool-writings#10]
Hi - when I install this via `composer install` to try to test v3, I got: 

```
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
```

... in std-out. I'm completely new to composer so I am not sure how to force it to use the log-recommended package locations. Is this something we can fix or, is it upstream?

**Comment by RickCogley** [comment]
Running `composer depends` shows what is requiring those abandoned packages it:

```
~/d/cool-site ❯❯❯ composer depends jakub-onderka/php-console-color                                                
jakub-onderka/php-console-highlighter  v0.4  requires  jakub-onderka/php-console-color (~0.2)
~/d/cool-site ❯❯❯ composer depends jakub-onderka/php-console-highlighter                                          
nunomaduro/collision  v3.0.1   requires  jakub-onderka/php-console-highlighter (0.3.*|0.4.*)
psy/psysh             v0.9.12  requires  jakub-onderka/php-console-highlighter (0.3.*|0.4.*)
```

However to fix ($1 to stackoverflow), just do `composer require` with the recommendations: 

```
> composer require php-parallel-lint/php-console-color
> composer require php-parallel-lint/php-console-highlighter
```

That will update the composer.json. Of course, not knowing what I'm doing, I'm wondering if what I did is kosher or not. Comments appreciated!

**Comment by jasonvarga** [comment]
It doesn't appear to output that anymore. But anyway, they are not errors so you can ignore them. 👍 

Just requiring the recommendations may suppress the errors but whatever packages were relying on the previous ones are still using them, so it doesn't really do anything.
