### ISSUE TITLE
Unpublished articles show in taxonomy list (and produce 404)

### ISSUE THREAD

**Issue by minthemiddle** [statamic/starter-kit-cool-writings#30]
When you have unpublished posts, they still show up on taxonomy indexes and produce 404s.
<img width="644" alt="Screenshot 2021-02-14 at 18 21 59" src="https://user-images.githubusercontent.com/1950766/107883835-9c192780-6ef1-11eb-872a-a3f67e8c65d2.png">

<img width="496" alt="Screenshot 2021-02-14 at 18 22 20" src="https://user-images.githubusercontent.com/1950766/107883833-9a4f6400-6ef1-11eb-92cb-62336be53894.png">

**Comment by duncanmcclean** [comment]
I believe this *may* be a duplicate of statamic/cms#2721 which is probably something that should be fixed in Core, rather than inside this starter kit.

**Comment by jackmcdade** [comment]
@duncanmcclean Agreed.
