### ISSUE TITLE
Topics page not loading

### ISSUE THREAD

**Issue by briannhinton** [statamic/starter-kit-cool-writings#42]
I tried three separate installs and all three times (and on a deploy) the topics page is loading empty. Individual topics seem to load when clicking a tag. The index exists and looks correctly setup in the code. I’d appreciate any help, and happy to provide additional info.

**Comment by jackmcdade** [comment]
Is this what you see? 

<img width="861" alt="CleanShot 2022-03-07 at 08 46 09@2x" src="https://user-images.githubusercontent.com/44739/157046111-ac8eb9e7-c1d9-44ac-8a70-310158cb74ce.png">

**Comment by briannhinton** [comment]
@jackmcdade correct!

**Comment by jackmcdade** [comment]
Same here. It has been fixed!

See: a02963440c0bb3920f4119d2e6fdc52a3b66f50e
