### ISSUE TITLE
Changed article collection issue

### ISSUE THREAD

**Issue by briannhinton** [statamic/starter-kit-cool-writings#43]
I changed the article collection to a note collection and now the URLs aren't generating. I'm sure it's a simple thing I need to do to get everything working correctly. I tried regenerating the cache, restarted valet (thinking it might be some valet cache thing), and I'm still having issues. The href is empty when viewing on the front-end. 

I changed all the article references, and nothing referencing the old article collection / blueprint exists.
And the collection is still showing on topic, home, etc.

<img width="676" alt="Screen Shot 2022-03-12 at 11 55 02 AM" src="https://user-images.githubusercontent.com/2288431/158027153-0c30d6c7-29f6-4062-a87f-acffef01790d.png">

**Comment by jackmcdade** [comment]
Did you change the route and/or mount settings? The Articles collection is mounted to the Articles entry in the Pages collection – i bet if you double check that all that is still connected after the rename it should work.

<img width="955" alt="CleanShot 2022-03-14 at 16 34 54@2x" src="https://user-images.githubusercontent.com/44739/158256695-4e8c72cd-774f-4c42-a2d4-891f7e854875.png">

<img width="348" alt="CleanShot 2022-03-14 at 16 35 03@2x" src="https://user-images.githubusercontent.com/44739/158256723-4e718c86-abde-48b0-a8a8-1616cb4ccbeb.png">

**Comment by briannhinton** [comment]
That was it! Rendering fine now. Thanks! Where can I find this in the code? I thought I looked everywhere.

**Comment by jackmcdade** [comment]
It would be in `collections/articles.yaml`. Glad you got it sorted!
