### ISSUE TITLE
Target class [Illuminate\Foundation\Vite] does not exist.

### ISSUE THREAD

**Issue by facu-alba** [statamic/starter-kit-cool-writings#46]
Hi everyone I get this error **Target class [Illuminate\Foundation\Vite] does not exist.** after running the command **statamic new mysite statamic/starter-kit-cool-writings**. Any idea to solve this?

**Comment by jackmcdade** [comment]
Are you running Statamic 4?On Jun 23, 2023, at 12:57 PM, facu-alba ***@***.***> wrote:﻿
Hi everyone I get this error Target class [Illuminate\Foundation\Vite] does not exist. after running the command statamic new mysite statamic/starter-kit-cool-writings. Any idea to solve this?

**Comment by duncanmcclean** [comment]
I'm going to close this issue now since it's been open for a while without any activity. This shouldn't be an issue if you're using Statamic 4 & Laravel 10.
