### ISSUE TITLE
failed to load a stylesheet from a url 

### ISSUE THREAD

**Issue by bub88** [statamic/starter-kit-cool-writings#47]
Problem with statamic starter-kit-cool-writings and ssg on netlify. After deploy my homepage the website have an error: “Failed to load resource: the server responded with a status of 404 ()".

- site-8b0104fe.css:1 
- /build/assets/site-8dda77ae.js:1

[website url](https://weltspot.netlify.app/)

**Comment by jasonvarga** [comment]
Check your devtools console and network tab and you'll be able to see the issue.

You are serving the site at `https://weltspot.netlify.app`, but your assets are pointed at `https://weltspot.com`.

Make sure you have the appropriate URLs set in `.env`.

**Comment by bub88** [comment]
I temporarily added a snippet for css and js in netlify, but that's just a stopgap solution. I guess I have to activate an addon for Vite.

**Comment by jasonvarga** [comment]
No addon needed. We have a tag. https://statamic.dev/tags/vite

**Comment by bub88** [comment]
> No addon needed. We have a tag. https://statamic.dev/tags/vite

What do I have to do then so that my homepage is generated correctly with SSG so that CSS and JS work?

**Comment by jasonvarga** [comment]
Set the right APP_URL in your .env

**Comment by bub88** [comment]
> Set the right APP_URL in your .env

I've tried everything possible. I also asked Netlify in the support forum. By the way, my main domain is weltspot.com. I suspect that SSG (Static Site Generator) cannot find the url for css and js exported by Vite. Which is also logical.

That's why I'm asking specifically. How to turn off or replace Vite when generating the static website so that the Antlers template uses the locally saved folders for css and js. Like in the Cool Writings demo website.

Thank you 😀

**Comment by jackmcdade** [comment]
Just don’t use vite then — use a regular style/script tags and point them at the css/JS files directly.

**Comment by bub88** [comment]
Thank you for your reply Mr. McDade. The solution was almost at hand. The only thing is that the hamburger menu doesn't work. I have included the following code for js. Do I need to add anything else?

`<script type="module" src="js/site.js"></script>`

**Comment by jackmcdade** [comment]
Looks like Alpine isn't loaded? You could try loading it from the CDN with:
```
<script src="//unpkg.com/alpinejs" defer></script>
```

Also, I see your script/style sources don't start with a slash, but should. Make sure you do `/js/` and not `js/` or they won't load on subpages.

**Comment by bub88** [comment]
> Looks like Alpine isn't loaded? You could try loading it from the CDN with:
> ```
> <script src="//unpkg.com/alpinejs" defer></script>
> ```
> 
> Also, I see your script/style sources don't start with a slash, but should. Make sure you do `/js/` and not `js/` or they won't load on subpages.
> 

Thank you for your response and your support. This works wonderfully. That was the final solution. I can now successfully build my blog on statamic cms with ssg 😀
