### ISSUE TITLE
Clarification on 2.0.2 vs. 2.0.3

### ISSUE THREAD

**Issue by JoshSalway** [statamic/starter-kit-cool-writings#53]
Hi Team,

I noticed that 2.0.3 was released on June 1, 2024, but 2.0.2 is still marked as the “Latest release” on the [Releases page](https://github.com/statamic/starter-kit-cool-writings/releases).

Is 2.0.3 required for updates or new installations? If not, why is it not marked as the “Latest release”?

For context, I installed the starter kit using this command:
`statamic new mysite statamic/starter-kit-cool-writings`

I noticed that my version is upgraded to Vite 5, which is the main change of 2.0.3

Thank you for clarifying!

Best regards,
Josh

**Comment by duncanmcclean** [comment]
It was just a mistake - fixed!
